[[top]]
= Changelog
include::attributes.adoc[]

All notable changes to this project will be documented on this page, and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

// == Date
//
// === Added
// === Changed
// === Deprecated
// === Removed
// === Fixed
// === Security

== Unreleased

=== Added
* A new section stub about <<advanced-features-of-the-type-system.adoc#transparency-and-opaqueness,transparency and opaqueness>> has been added.

=== Changed
* The tip that <<advanced-features-of-the-type-system.adoc#tip-use-literal-types-in-favor-of-enums,literal types should be used in favor of string based enums>> has been extended to link the section about <<advanced-features-of-the-type-system.adoc#transparency-and-opaqueness,transparency and opaqueness>>.

=== Fixed
* The section about <<basics-of-typescript.adoc#constant-enums,constant enums>> was violating the style guide. It has been rewritten to no longer contain sentence fragments. {docs-repo-issues}/1[#1]

== v0.1.0 - 2019-10-16

=== Added
* Introduced a Changelog page where all notable changes to this project will be documented.

=== Changed
* Editor screenshots have been updated to use a light theme to be more pleasant to watch (was previously a dark theme).
* The table of contents expands all headers right away (was previously hiding certain sections).
* Replaced informal occurences of the word _typo(s)_ with the word _misspelling(s)_.

=== Fixed
* A misspelling of the word _operator_ in the section about the <<advanced-features-of-the-type-system.adoc#indexed-access-operator,indexed access operator>>.