[[top]]
= Changelog
include::attributes.adoc[]

All notable changes to this project will be documented on this page, and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

// == Date
//
// === Added
// === Changed
// === Deprecated
// === Removed
// === Fixed
// === Security

== Unreleased

=== Added
* Type hints are now displayed after declarations where Typescript can infer the respective types automatically.
* {docs-repo-issues}/7[#7] - A note about the difference of types vs. interfaces has been added to the section about <<basics-of-typescript.adoc#type-aliases,type aliases>>.
* A new section about <<basics-of-typescript.adoc#constraints-and-defaults,constraints and defaults>> for generic types has been added.
* A new section about <<advanced-features-of-the-type-system.adoc#mapped-types,mapped types>> has been added.
* A new section about <<advanced-features-of-the-type-system.adoc#conditional-types,conditional types>> has been added.
* A new section about <<advanced-features-of-the-type-system.adoc#transparency-and-opaqueness,transparency and opaqueness>> has been added.

=== Changed
* The tip that <<advanced-features-of-the-type-system.adoc#tip-use-literal-types-in-favor-of-enums,literal types should be used in favor of string based enums>> has been extended to link the section about <<advanced-features-of-the-type-system.adoc#transparency-and-opaqueness,transparency and opaqueness>>.
* Replaced the buggy previous version of the Prism syntax highlighting library with a custom static Textmate-based transformer allowing for more features and annotations in code.
* Compiler errors are no longer referenced via numbered bullets. Instead they are highlighted in red and wavy underline. Hovering over those will display a popover with the error message.
* {docs-repo-issues}/5[#5] - The section about <<basics-of-typescript.adoc#null-and-undefined,null and undefined>> has been reworked to better distinguish between both types and their usage.

=== Fixed
* {docs-repo-issues}/1[#1] - The section about <<basics-of-typescript.adoc#constant-enums,constant enums>> was violating the style guide. It has been rewritten to no longer contain sentence fragments.
* {docs-repo-issues}/2[#2] - The section about <<basics-of-typescript.adoc#intersection-types,intersection types>> was violating the style guide. It has been rewritten to no longer contain sentence fragments.

== v0.1.0 - 2019-10-16

=== Added
* Introduced a Changelog page where all notable changes to this project will be documented.

=== Changed
* Editor screenshots have been updated to use a light theme to be more pleasant to watch (was previously a dark theme).
* The table of contents expands all headers right away (was previously hiding certain sections).
* Replaced informal occurences of the word _typo(s)_ with the word _misspelling(s)_.

=== Fixed
* A misspelling of the word _operator_ in the section about the <<advanced-features-of-the-type-system.adoc#indexed-access-operator,indexed access operator>>.