// Document conventions:
// * One sentence per line
// * US spelling (single t in formating, ize not ise, color)
// * No highlighting breaking the flow of reading
// * e.g. not eg
// * The author is "we"
// * The reader is "you"
// * DRY URLs
// * You define parameters, and you make arguments
// * Admonitions:
// ** Note admonitions: Offer additional information that the reader may find helpful but that is not crucial to the content.
// ** Important admonitions: Call out things that the reader really should know when working with the content.
// ** Tip admonitions: Offer shortcuts or other details that make things easier or faster for the reader.
// ** Caution admonitions: Let readers know of common errors or other issues that may slow their work or send them down an unproductive path.
// ** Warning admonitions: Let readers know of risks or other issues that may cause severe problems, most notably data loss (including loss of information from databases, file systems, and version control systems).
[[react-typescript-bootcamp-docs]]
= Mob Training: React / Typescript
Christian Ivicevic <https://github.com/ChristianIvicevic[@ChristianIvicevic]>

include::attributes.adoc[]
:!toc:

[NOTE]
If you find errors or omissions in this document, please don't hesitate to {docs-repo-issues}[submit an issue or open a pull request] with a fix.
We also encourage you to ask questions and discuss any aspects of the project.

The training material consists of the following sections:

[horizontal]
<<about-the-training.adoc#,About the Training>> :: General information about the training itself including the scope, requirements and details on the training material.
<<basics-of-typescript.adoc#,Basics of Typescript>> :: Introduction to the basics of the Typescript programming language, advantages of Typescript over Javascript and the basic data types and their compositions.
<<advanced-features-of-the-type-system.adoc#,Advanced Features of the Type System>> :: This section summarizes more advanced topics of the Typescript type system and presents powerful types and their use-cases.

The training material consists of the following appendices:

[horizontal]
<<appendix-utility-types.adoc#,Utility Types>> :: Frequently used utility types that are mostly part of the official Typescript compiler.
<<appendix-changelog.adoc#,Changelog>> :: All notable changes to this project will be documented on this page.
